version: '3'
services:
  php:
    container_name: laravel_php 
    # ./docker/phpにDockerfileを探しにいく。
    build: ./docker/php
    # ローカルにある「server」フォルダとDockerにある「/var/www/server」フォルダを同期させる。
    volumes:
    - ./server:/var/www

  nginx:
    # nginxをインストール
    image: nginx
    container_name: laravel_nginx 
    # enginxのポートも合わせる。
    ports:
    - "8081:8081" # ホスト側のポート番号:コンテナ内のポート番号
    volumes:
    # ローカルにある「server」フォルダとDockerにある「/var/www/server」フォルダを同期させる。
    - ./server:/var/www
    # ローカルにある「nginx/default.conf」とDockerにある「/etc/nginx/conf.d/default.conf」を同期させる。
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # phpが起動した後にnginxを起動させる。
    depends_on:
    - php
  db:
    image: mysql:5.7
    # 重複するとエラー
    container_name: laravel_mysql 
    ports:
    - "3308:3308"
    volumes:
      ## MYSQLがデータを保存する場所
      - ./db:/var/lib/mysql
      - ./my_conf:/etc/mysql/conf.d
    # MYSQLに接続するための情報 
    environment:
      #必須 rootのパスワード
      MYSQL_ROOT_PASSWORD: jksdkejfdskfds 
      # 新規データベースし、そこにアクセスできるユーザーを作成
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: kjfdslkjfdsfds
      TZ: 'Asia/Tokyo'
    # Dockerの公式MySQLの文字コードをutf8mb4に設定する
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci